export declare class Scheduler {
    cronExpression: string;
    isAltered: boolean;
    everyMinute(): Scheduler;
    everyFiveMinutes(): Scheduler;
    everyTenMinutes(): Scheduler;
    everyFifteenMinutes(): Scheduler;
    everyThirtyMinutes(): Scheduler;
    hourly(): Scheduler;
    hourlyAt(offset: number): Scheduler;
    daily(): Scheduler;
    at(time: string): Scheduler;
    dailyAt(time: string): Scheduler;
    twiceDaily(first: number, second: number): Scheduler;
    weekdays(): Scheduler;
    weekends(): Scheduler;
    mondays(): Scheduler;
    tuesdays(): Scheduler;
    wednesdays(): Scheduler;
    thursdays(): Scheduler;
    fridays(): Scheduler;
    saturdays(): Scheduler;
    sundays(): Scheduler;
    weekly(): Scheduler;
    weeklyOn(day: string | number, time: string): Scheduler;
    monthly(): Scheduler;
    monthlyOn(day: number, time: string): Scheduler;
    twiceMonthly(first: number, second: number): Scheduler;
    quarterly(): Scheduler;
    yearly(): Scheduler;
    days(day: number): Scheduler;
    spliceIntoPosition(position: number, value: any): Scheduler;
    cron(expression: string): Scheduler;
}
